SupplyCrates:
  time:
    auto_end_after_start: 600
    interval_start: 1800
  hologram:
   #Set to message: [] to disable!
    message:
      - '&8&m===&c Supply Crate&8 &m==='
  particle:
    #Set to type: '' to disable!
    type: SMOKE_NORMAL
  crate:
    amount_of_items: 10
    type: CHEST
    falling_block: BEACON
    random_locations:
      #If enabled it will choose 10 random locations to spawn Supply Crates.
      enabled: false
      amount: 10
    locations: []
    items:
      '1':
        material: GOLDEN_APPLE:1
        amount: 1
        name: '&fSupply Crate Gapple'
        lore:
          - '&dExclusive &e&nGapple&d from a Supply Crate'
        chance: 75
      '2':
        material: DIAMOND_HELMET
        amount: 1
        name: '&fSupply Crate Helmet'
        lore:
          - '&dExclusive &e&nDiamond Helmet&d from a Supply Crate'
        enchants:
          - protection:4
          - unbreaking:3
        chance: 1
      '3':
        material: DIAMOND_CHESTPLATE
        amount: 1
        name: '&fSupply Crate Chestplate'
        lore:
          - '&dExclusive &e&nDiamond Chestplate&d from a Supply Crate'
        enchants:
          - protection:4
          - unbreaking:3
        chance: 2
      '4':
        material: DIAMOND_LEGGINGS
        amount: 1
        name: '&fSupply Crate Leggings'
        lore:
          - '&dExclusive &e&nDiamond Leggings&d from a Supply Crate'
        enchants:
          - protection:4
          - unbreaking:3
        chance: 1
      '5':
        material: DIAMOND_BOOTS
        amount: 1
        name: '&fSupply Crate Boots'
        lore:
          - '&dExclusive &e&nDiamond Boots&d from a Supply Crate'
        enchants:
          - protection:4
          - unbreaking:3
        chance: 2
      '6':
        commands:
          - eco give {player} 2000
        chance: 2